
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 12 00:51:20 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATER_OR_EQUAL = 30;
  public static final int CONST = 5;
  public static final int CHAR = 23;
  public static final int MINUS_MINUS = 40;
  public static final int CONTINUE = 36;
  public static final int LPAREN = 7;
  public static final int GREATER = 29;
  public static final int SEMI = 6;
  public static final int LESS = 31;
  public static final int FOR = 26;
  public static final int MINUS = 16;
  public static final int RPAREN = 8;
  public static final int AND = 45;
  public static final int LESS_OR_EQUAL = 32;
  public static final int OR = 44;
  public static final int BOOL = 22;
  public static final int COMMA = 9;
  public static final int CLASS = 33;
  public static final int DIV = 18;
  public static final int PLUS = 13;
  public static final int IF = 24;
  public static final int DOT = 38;
  public static final int ABSTRACT = 35;
  public static final int EOF = 0;
  public static final int PLUS_PLUS = 39;
  public static final int RETURN = 12;
  public static final int EQUAL = 14;
  public static final int NEW = 43;
  public static final int error = 1;
  public static final int MUL = 17;
  public static final int NUMBER = 20;
  public static final int MOD = 19;
  public static final int BREAK = 37;
  public static final int IDENT = 21;
  public static final int RSQUARE_BRACKET = 42;
  public static final int VOID = 15;
  public static final int NOTEQUAL_COMPARATION = 28;
  public static final int LBRACE = 3;
  public static final int ELSE = 25;
  public static final int READ = 11;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 34;
  public static final int PROG = 2;
  public static final int EQUAL_COMPARATION = 27;
  public static final int LSQUARE_BRACKET = 41;
  public static final int PRINT = 10;
}

